library(gplots)
a<-read.table("../Desktop/Differential metabolites_Brain.txt", header = T)
a <- sapply(a[,c(2:24)], as.numeric)
dat.n<-scale(t(a))
dat.n[is.na(dat.n)]<-0
dat.tn=t(dat.n)
round(colMeans(dat.n),1)
apply(dat.n,2,sd)
d1<-dist(dat.n,method = "euclidean",diag = FALSE,upper = FALSE)
round(d1,3)
d2<-dist(dat.tn,method = "euclidean",diag = FALSE,upper = TRUE)
c1<-hclust(d1, method = "average",members = NULL)
c2<-hclust(d2, method = "average",members = NULL)
par(mfrow=c(2,1),cex=0.5)
plot(c1);plot(c2)
my_palette<-colorRampPalette(c("blue","black","yellow"))(n=25)
par(cex.main=0.75)
cutoff<-6
cluster<-cutree(c2, k=cutoff)
mycolhc<-rainbow(max(cluster),start = 0.1, end = 0.9)
mycolhc<-mycolhc[as.vector(cluster)]
heatmap.2(dat.tn, Colv=as.dendrogram(c1),Rowv=as.dendrogram(c2),density.info="histogram",trace="none",col=my_palette,cexRow=1,cexCol=1,RowSideColors=mycolhc)
library(clValid)
dunn(d2, cluster)